version: "2"
services:
  mysql:
    container_name: knowledge-xchange-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "knowledge-xchange"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
