version: "2"
services:
  mysql:
    container_name: knowledge-xchange-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "knowledge-xchange"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3306:3306"
    volumes:
      - knowledge-xchange-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  knowledge-xchange-data:
